[package]
name = "tokio-curl"
version = "0.1.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-curl"
homepage = "https://github.com/tokio-rs/tokio-curl"
documentation = "https://tokio-rs.github.io/tokio-curl"
description = """
An implementation of an asynchronous HTTP client using futures backed by
libcurl.
"""

[dependencies]
curl = "0.3.6"
futures = "0.1"
tokio-core = "0.1"
log = "0.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio = "0.6"
slab = "0.3"
scoped-tls = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
ws2_32-sys = "0.2"

[dev-dependencies]
env_logger = "0.3"

[replace]
'tokio-core:0.1.0' = { git = "https://github.com/tokio-rs/tokio-core" }
'futures:0.1.3' = { git = "https://github.com/alexcrichton/futures-rs" }
